### ISSUE TITLE
Unable to run on Mac OSX 12.6.4

### ISSUE THREAD

**Issue by cometsong** [andreas-p/admin4#11]
Admin4 version:  3.0.2
MacOS version: 12.6.4

Tried running GUI from: 
- the downloaded .dmg file
- ~/Applications folder
- Admin4/Contents/MacOs/Admin4 file directly
- Ctrl-click selecting 'Open' (as Apple help docs suggest as well)

None worked; all gave similar errors dialogs:  😦 
`“Admin4” cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware.`
with suggestions of ejecting disk or moving file to trash.

Running directly from command line _does_ start the app 🎉 , but that doesn't get the other gui tactics to work. Bummer.

**Comment by andreas-p** [comment]
You need to enable non-verified developer for this.
