### ISSUE TITLE
modBind: Allow host to be . (not @) to allow PRZ zones

### ISSUE THREAD

**Issue by nreilly** [andreas-p/admin4#15]
Small change to support [PRZ](https://downloads.isc.org/isc/bind9/9.18.21/doc/arm/html/chapter6.html#dns-firewalls-and-response-policy-zones) 

> All DNS RPZ rules are expressed as resource record sets (RRsets), and the way to express a “force a name-does-not-exist condition” is by adding a CNAME pointing to the root domain (.). In practice this looks like:

```
$ORIGIN rpz.example.com.
malicious1.org          CNAME .
*.malicious1.org        CNAME .
malicious2.org          CNAME .
*.malicious2.org        CNAME .
```

It appears this change in modBind/_dns.py makes this work:
``` diff
 def DnsName(*args):
   lst=[]
-  for arg in args:
-    if isinstance(arg, list):
-      lst.extend(arg)
-    else:
-      lst.extend(arg.split('.'))
-      
+  if(args ==(".",)):
+    lst = [b""]
+  else:
+    for arg in args:
+      if isinstance(arg, list):
+        lst.extend(arg)
+      else:
+        lst.extend(arg.split('.'))
   return Name(lst)
```

**Comment by andreas-p** [comment]
Fixed in https://github.com/andreas-p/admin4/commit/897608adc6cdb4bfc83b5c5b812f30569f4e1737, thanks for reporting.
