### ISSUE TITLE
Can't create new APL record

### ISSUE THREAD

**Issue by nreilly** [andreas-p/admin4#16]
When trying to create a new APL ([RFC3123](https://datatracker.ietf.org/doc/html/rfc3123.html)) record, the contextual menu disappears and no new window appears to enter details. APL records are used in catalog zones to [specify access control lists](https://bind9.readthedocs.io/en/latest/chapter6.html#catalog-zone-custom-properties).

**Comment by andreas-p** [comment]
When creating a new RR, Admin4 tries to assemble an empty Rdataset, by creating cls.from_text with all fields set to "0", which usually works. Unfortunately, APL expects "1:127.0.0.1/32" . 
This issue isn't restricted to APL, but many more that need more than a "0" as placeholder value, any of them need examination, what fits as dummy initial value (which is used to determine the correct type handling only).
All "exotic" RR types need to be examined, and a workable initial value specified, extracted from the RFCs. I currently don't have for that.

**Comment by andreas-p** [comment]
There's experimental code pushed, handling APL, but the rest is TODO.

**Comment by andreas-p** [comment]
Well the APL (and probably some other RR types) code need special typed parameters. This would require specific programming I'm not willing to do at the moment.
Editing those types should be disabled.
