### ISSUE TITLE
Unable to run on Mac OSX 10.x

### ISSUE THREAD

**Issue by dustinromey** [andreas-p/admin4#2]
Tried versions 2.1.7 and 2.1.6 downloaded from Sourceforge.  Below is the Console output for Admin4:

8/10/14 6:42:46.000 AM kernel[0]: hfs: mounted Admin4 on device disk1s1
8/10/14 6:42:46.173 AM mds[60]: (Normal) Volume: volume:0x7f891aa44400 *********\* Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/Admin4
8/10/14 6:42:52.519 AM CoreServicesUIAgent[14210]: Saving rejection record:
Rejected URL=file:///Volumes/Admin4/Admin4.app/
App URL=file:///Volumes/Admin4/Admin4.app/
8/10/14 6:42:52.522 AM com.apple.launchd.peruser.501[277]: ([0x0-0x486486].org.admin4[14226]) Exited: Killed: 9
8/10/14 6:43:06.627 AM Admin4[14229]: Traceback (most recent call last):
8/10/14 6:43:06.627 AM Admin4[14229]:   File "/Volumes/Admin4/Admin4.app/Contents/Resources/**boot**.py", line 117, in <module>
8/10/14 6:43:06.627 AM Admin4[14229]:     _run()
8/10/14 6:43:06.627 AM Admin4[14229]:   File "/Volumes/Admin4/Admin4.app/Contents/Resources/__boot__.py", line 108, in _run
8/10/14 6:43:06.628 AM Admin4[14229]:     exec(compile(source, path, 'exec'), globals(), globals())
8/10/14 6:43:06.628 AM Admin4[14229]:   File "/Volumes/Admin4/Admin4.app/Contents/Resources/admin4.py", line 15, in <module>
8/10/14 6:43:06.628 AM Admin4[14229]:     main.main(sys.argv)
8/10/14 6:43:06.628 AM Admin4[14229]:   File "/Volumes/Admin4/Admin4.app/Contents/Resources/main.py", line 274, in main
8/10/14 6:43:06.628 AM Admin4[14229]:     opts, args = getopt.getopt(argv[1:], "m:n:", ["modules=", "name="])
8/10/14 6:43:06.628 AM Admin4[14229]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 90, in getopt
8/10/14 6:43:06.628 AM Admin4[14229]:     opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
8/10/14 6:43:06.629 AM Admin4[14229]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 190, in do_shorts
8/10/14 6:43:06.629 AM Admin4[14229]:     if short_has_arg(opt, shortopts):
8/10/14 6:43:06.629 AM Admin4[14229]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 206, in short_has_arg
8/10/14 6:43:06.629 AM Admin4[14229]:     raise GetoptError('option -%s not recognized' % opt, opt)
8/10/14 6:43:06.629 AM Admin4[14229]: getopt.GetoptError: option -p not recognized
8/10/14 6:43:06.695 AM Admin4[14229]: Admin4 Error
8/10/14 6:43:06.696 AM Admin4[14229]: 2014-08-10 06:43:06.694 Admin4[14229:707] Admin4 Error
8/10/14 6:43:09.550 AM com.apple.launchd.peruser.501[277]: ([0x0-0x487487].org.admin4[14229]) Exited with code: 255
8/10/14 6:44:09.379 AM Admin4[14261]: Traceback (most recent call last):
8/10/14 6:44:09.379 AM Admin4[14261]:   File "/Applications/Admin4.app/Contents/Resources/__boot__.py", line 117, in <module>
8/10/14 6:44:09.379 AM Admin4[14261]:     _run()
8/10/14 6:44:09.380 AM Admin4[14261]:   File "/Applications/Admin4.app/Contents/Resources/__boot__.py", line 108, in _run
8/10/14 6:44:09.380 AM Admin4[14261]:     exec(compile(source, path, 'exec'), globals(), globals())
8/10/14 6:44:09.380 AM Admin4[14261]:   File "/Applications/Admin4.app/Contents/Resources/admin4.py", line 15, in <module>
8/10/14 6:44:09.380 AM Admin4[14261]:     main.main(sys.argv)
8/10/14 6:44:09.380 AM Admin4[14261]:   File "/Applications/Admin4.app/Contents/Resources/main.py", line 274, in main
8/10/14 6:44:09.380 AM Admin4[14261]:     opts, args = getopt.getopt(argv[1:], "m:n:", ["modules=", "name="])
8/10/14 6:44:09.381 AM Admin4[14261]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 90, in getopt
8/10/14 6:44:09.381 AM Admin4[14261]:     opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
8/10/14 6:44:09.381 AM Admin4[14261]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 190, in do_shorts
8/10/14 6:44:09.381 AM Admin4[14261]:     if short_has_arg(opt, shortopts):
8/10/14 6:44:09.381 AM Admin4[14261]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 206, in short_has_arg
8/10/14 6:44:09.381 AM Admin4[14261]:     raise GetoptError('option -%s not recognized' % opt, opt)
8/10/14 6:44:09.381 AM Admin4[14261]: getopt.GetoptError: option -p not recognized
8/10/14 6:44:09.447 AM Admin4[14261]: Admin4 Error
8/10/14 6:44:09.447 AM Admin4[14261]: 2014-08-10 06:44:09.446 Admin4[14261:707] Admin4 Error
8/10/14 6:44:11.198 AM com.apple.launchd.peruser.501[277]: ([0x0-0x489489].org.admin4[14261]) Exited with code: 255
8/10/14 6:44:48.000 AM kernel[0]: hfs: unmount initiated on Admin4 on device disk1s1
8/10/14 6:46:55.000 AM kernel[0]: hfs: mounted Admin4 on device disk1s1
8/10/14 6:46:55.114 AM mds[60]: (Normal) Volume: volume:0x7f891b9ef000 *********\* Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/Admin4
8/10/14 6:47:35.580 AM CoreServicesUIAgent[14369]: Saving rejection record:
Rejected URL=file:///Volumes/Admin4/Admin4.app/
App URL=file:///Volumes/Admin4/Admin4.app/
8/10/14 6:47:35.582 AM com.apple.launchd.peruser.501[277]: ([0x0-0x4ab4ab].org.admin4[14367]) Exited: Killed: 9
8/10/14 6:47:49.446 AM CoreServicesUIAgent[14369]: Saving rejection record:
Rejected URL=file:///Applications/Admin4.app/
App URL=file:///Applications/Admin4.app/
8/10/14 6:47:49.448 AM com.apple.launchd.peruser.501[277]: ([0x0-0x4ad4ad].org.admin4[14376]) Exited: Killed: 9
8/10/14 6:47:59.645 AM Admin4[14378]: Traceback (most recent call last):
8/10/14 6:47:59.645 AM Admin4[14378]:   File "/Applications/Admin4.app/Contents/Resources/__boot__.py", line 117, in <module>
8/10/14 6:47:59.645 AM Admin4[14378]:     _run()
8/10/14 6:47:59.645 AM Admin4[14378]:   File "/Applications/Admin4.app/Contents/Resources/__boot__.py", line 108, in _run
8/10/14 6:47:59.645 AM Admin4[14378]:     exec(compile(source, path, 'exec'), globals(), globals())
8/10/14 6:47:59.646 AM Admin4[14378]:   File "/Applications/Admin4.app/Contents/Resources/admin4.py", line 15, in <module>
8/10/14 6:47:59.646 AM Admin4[14378]:     main.main(sys.argv)
8/10/14 6:47:59.646 AM Admin4[14378]:   File "/Applications/Admin4.app/Contents/Resources/main.py", line 274, in main
8/10/14 6:47:59.646 AM Admin4[14378]:     opts, args = getopt.getopt(argv[1:], "m:n:", ["modules=", "name="])
8/10/14 6:47:59.646 AM Admin4[14378]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 90, in getopt
8/10/14 6:47:59.646 AM Admin4[14378]:     opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
8/10/14 6:47:59.647 AM Admin4[14378]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 190, in do_shorts
8/10/14 6:47:59.647 AM Admin4[14378]:     if short_has_arg(opt, shortopts):
8/10/14 6:47:59.647 AM Admin4[14378]:   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/getopt.py", line 206, in short_has_arg
8/10/14 6:47:59.647 AM Admin4[14378]:     raise GetoptError('option -%s not recognized' % opt, opt)
8/10/14 6:47:59.647 AM Admin4[14378]: getopt.GetoptError: option -p not recognized
8/10/14 6:47:59.712 AM Admin4[14378]: Admin4 Error
8/10/14 6:47:59.712 AM Admin4[14378]: 2014-08-10 06:47:59.711 Admin4[14378:707] Admin4 Error
8/10/14 6:48:03.142 AM com.apple.launchd.peruser.501[277]: ([0x0-0x4ae4ae].org.admin4[14378]) Exited with code: 255

**Comment by andreas-p** [comment]
No more comments, closing now.
